/**
 * Icons Index
 *
 * Export Icon component and icon registry.
 * Usage: <Icon name="arrow-up" size={16} />
 */

export { default as Icon } from './Icon.jsx';

// Icon Registry - Complete list of all 341 icons
export const ICONS = {
  // Rack (113)
  rack: [
    'ascii-back',
    'ascii-block',
    'ascii-dash',
    'ascii-dot',
    'ascii-equal',
    'ascii-hash',
    'ascii-pipe',
    'ascii-plus',
    'ascii-slash',
    'ascii-x',
    'cable-lock',
    'cable-off',
    'cable-on',
    'cable-trans',
    'cable-unlock',
    'cap-butt',
    'cap-round',
    'cap-square',
    'chevron-down',
    'chevron-left',
    'chevron-right',
    'chevron-up',
    'clr-anl',
    'clr-comp',
    'clr-mono',
    'clr-tri',
    'curve-exp',
    'curve-log',
    'dith-cross',
    'dith-crt',
    'dith-diamond',
    'dith-flow',
    'dith-flower',
    'dith-gear',
    'dith-glitch',
    'dith-grid',
    'dith-hex',
    'dith-htone',
    'dith-melt',
    'dith-radial',
    'dith-xhatch',
    'filter-bp',
    'filter-hp',
    'filter-lp',
    'filter-notch',
    'gen-color',
    'gen-gradient',
    'gen-pattern',
    'gen-wave',
    'grad-con',
    'grad-lin',
    'grad-rad',
    'line-circle',
    'line-grid',
    'line-line',
    'line-lissa',
    'line-spiral',
    'logic-and',
    'logic-nand',
    'logic-nor',
    'logic-not',
    'logic-or',
    'logic-xor',
    'nav-create',
    'nav-home',
    'nav-library',
    'nav-rack',
    'nav-settings',
    'ptrn-checker',
    'ptrn-dot',
    'ptrn-stripe',
    'radial-circle',
    'radial-default',
    'radial-hex',
    'radial-random',
    'radial-rect',
    'radial-star',
    'radial-triangle',
    'ramp-down',
    'ramp-tri',
    'ramp-up',
    'seq-a',
    'seq-b',
    'seq-c',
    'seq-d',
    'shape-cube',
    'shape-cyl',
    'shape-ico',
    'shape-octa',
    'shape-sphere',
    'shape-tetra',
    'shape-torus',
    'shaper-clip',
    'shaper-exp',
    'shaper-fold',
    'shaper-log',
    'shaper-scurve',
    'shaper-sine',
    'shaper-step',
    'shaper-wrap',
    'tr-carets',
    'tr-fwd',
    'tr-inf',
    'tr-left',
    'tr-pause',
    'tr-rew',
    'tr-right',
    'tr-skip',
    'wave-rnd',
    'wave-saw',
    'wave-sin',
    'wave-sqr',
    'wave-tri',
  ],

  // Navigation (21)
  navigation: [
    'arrow-cross',
    'arrow-down',
    'arrow-downright',
    'arrow-expand',
    'arrow-left',
    'arrow-right',
    'arrow-up',
    'caret-down',
    'caret-left',
    'caret-right',
    'caret-up',
    'chevron-down',
    'chevron-right',
    'chevron-up',
    'control-arrow-back',
    'control-arrow-end',
    'control-arrow-forward',
    'control-arrow-start',
    'external-link',
    'menu',
    'x',
  ],

  // Actions & Controls (28)
  actions: [
    'check',
    'copy',
    'cross',
    'download',
    'edit',
    'filter',
    'maximize',
    'minimize',
    'minus',
    'move',
    'plus',
    'redo',
    'refresh',
    'rotate',
    'rotate-left',
    'rotate-right',
    'save',
    'search',
    'search-line',
    'settings-01',
    'settings-02',
    'share',
    'snap',
    'trash',
    'undo',
    'upload',
    'zoom-in',
    'zoom-out',
  ],

  // Files & Documents (16)
  files: [
    'add-file',
    'attachment',
    'book-open',
    'bookmark',
    'clipboard-1',
    'clipboard-2',
    'file',
    'file-image',
    'file-text',
    'file-video',
    'folder-01',
    'folder-02',
    'folder-open',
    'journal',
    'manual-empty',
    'page',
  ],

  // Communication (9)
  communication: [
    'alarm-bell',
    'dual-opponent',
    'in-going',
    'interactive',
    'mail',
    'message-circle',
    'message-square',
    'phone',
    'send',
  ],

  // User & Authentication (16)
  user: [
    'flag',
    'heart-1',
    'heart-2',
    'key',
    'lock',
    'log-in',
    'log-out',
    'shield',
    'social-facebook',
    'social-linkedin',
    'social-twitter',
    'star',
    'unlock',
    'user',
    'user-plus',
    'users',
  ],

  // Status & Feedback (9)
  status: [
    'alert-circle',
    'alert-triangle',
    'check-circle',
    'eye-off',
    'eye-on',
    'help-circle',
    'info',
    'loader',
    'x-circle',
  ],

  // Media (22)
  media: [
    'camera',
    'camera-off',
    'control-pause',
    'control-play',
    'control-stop',
    'fast-forward',
    'image',
    'mic',
    'mic-off',
    'repeat',
    'repeat-1',
    'rewind',
    'shuffle',
    'skip-back',
    'skip-forward',
    'stop',
    'video',
    'video-off',
    'volume',
    'volume-1',
    'volume-2',
    'volume-x',
  ],

  // Time & Calendar (9)
  time: [
    'calendar',
    'calendar-check',
    'calendar-days',
    'clock',
    'clock-alert',
    'clock-rotate-left',
    'history',
    'stopwatch',
    'timer',
  ],

  // Layout & UI (21)
  layout: [
    'columns',
    'component',
    'grid-01',
    'grid-02',
    'grid-03',
    'grid-04',
    'grid-05',
    'grid-06',
    'layers',
    'layout',
    'layout-01',
    'layout-02',
    'layout-03',
    'list-01',
    'list-02',
    'more-horizontal',
    'more-vertical',
    'panel-left',
    'panel-right',
    'row',
    'sidebar',
  ],

  // Editing & Content (18)
  editing: [
    'align-center',
    'align-left',
    'align-right',
    'bold',
    'brush',
    'color',
    'flip-y',
    'italic',
    'list-ordered',
    'list-unordered',
    'pen',
    'pencil',
    'text-01',
    'text-02',
    'type-01',
    'type-02',
    'type-03',
    'underline',
  ],

  // System & Tools (15)
  system: [
    'atomic-atom',
    'atomic-lifeform',
    'atomic-molecule',
    'atomic-organism',
    'battery',
    'code',
    'database',
    'frequency',
    'library',
    'power',
    'roadmap',
    'server',
    'terminal',
    'wifi',
    'wifi-off',
  ],

  // Theme & Display (5)
  theme: [
    'contrast',
    'monitor',
    'moon',
    'sun',
    'theme-toggle',
  ],

  // E-commerce & Shopping (8)
  ecommerce: [
    'credit-card',
    'dollar-sign',
    'gift',
    'package',
    'receipt',
    'shopping-bag',
    'shopping-cart',
    'tag',
  ],

  // Stats & Data Visualization (15)
  stats: [
    'stat-abacus',
    'stat-chart-a',
    'stat-chart-b',
    'stat-chart-c',
    'stat-crown',
    'stat-cycle',
    'stat-donut',
    'stat-medalion',
    'stat-pie',
    'stat-pie-c',
    'stat-rocket',
    'stat-stat',
    'stat-winner',
    'trending-down',
    'trending-up',
  ],

  // Shapes & Geometric (6)
  shapes: [
    'circle',
    'cone',
    'diamond',
    'triangle',
    'wave',
    'wheel',
  ],

  // Miscellaneous (10)
  misc: [
    'align-auto',
    'bolt',
    'bucket',
    'foundation',
    'home-1',
    'home-2',
    'instance',
    'location',
    'pills',
    'rabbit',
  ],

  // Another Creation — brand iconography (1)
  anotherCreation: [
    'signature-thick',
  ],
};

// Flat array of all icon names
export const ALL_ICONS = Object.values(ICONS).flat();

// Helper to check if an icon exists
export const hasIcon = (name) => ALL_ICONS.includes(name);

// Get category for an icon
export const getCategory = (name) => {
  for (const [category, icons] of Object.entries(ICONS)) {
    if (icons.includes(name)) {
      return category;
    }
  }
  return null;
};
